<select name="quickdashicons">
<option  value=""><?php _e( "please select", "textdomain" ); ?></option>
<option  value="admin-appearance"><i class="dashicons dashicons-admin-appearance"></i> dashicons-admin-appearance</option>
<option  value="admin-collapse"><i class="dashicons dashicons-admin-collapse"></i> dashicons-admin-collapse</option>
<option  value="admin-comments"><i class="dashicons dashicons-admin-comments"></i> dashicons-admin-comments</option>
<option  value="admin-customizer"><i class="dashicons dashicons-admin-customizer"></i> dashicons-admin-customizer</option>
<option  value="admin-generic"><i class="dashicons dashicons-admin-generic"></i> dashicons-admin-generic</option>
<option  value="admin-home"><i class="dashicons dashicons-admin-home"></i> dashicons-admin-home</option>
<option  value="admin-links"><i class="dashicons dashicons-admin-links"></i> dashicons-admin-links</option>
<option  value="admin-media"><i class="dashicons dashicons-admin-media"></i> dashicons-admin-media</option>
<option  value="admin-multisite"><i class="dashicons dashicons-admin-multisite"></i> dashicons-admin-multisite</option>
<option  value="admin-network"><i class="dashicons dashicons-admin-network"></i> dashicons-admin-network</option>
<option  value="admin-page"><i class="dashicons dashicons-admin-page"></i> dashicons-admin-page</option>
<option  value="admin-plugins"><i class="dashicons dashicons-admin-plugins"></i> dashicons-admin-plugins</option>
<option  value="admin-post"><i class="dashicons dashicons-admin-post"></i> dashicons-admin-post</option>
<option  value="admin-settings"><i class="dashicons dashicons-admin-settings"></i> dashicons-admin-settings</option>
<option value="admin-site-alt"><i class="dashicons dashicons-admin-site-alt"></i> <em>dashicons-admin-site-alt</em></option>
<option value="admin-site-alt2"><i class="dashicons dashicons-admin-site-alt2"></i> <em>dashicons-admin-site-alt2</em></option>
<option value="admin-site-alt3"><i class="dashicons dashicons-admin-site-alt3"></i> <em>dashicons-admin-site-alt3</em></option>
<option  value="admin-site"><i class="dashicons dashicons-admin-site"></i> dashicons-admin-site</option>
<option  value="admin-tools"><i class="dashicons dashicons-admin-tools"></i> dashicons-admin-tools</option>
<option  value="admin-users"><i class="dashicons dashicons-admin-users"></i> dashicons-admin-users</option>
<option  value="album"><i class="dashicons dashicons-album"></i> dashicons-album</option>
<option  value="align-center"><i class="dashicons dashicons-align-center"></i> dashicons-align-center</option>
<option  value="align-left"><i class="dashicons dashicons-align-left"></i> dashicons-align-left</option>
<option  value="align-none"><i class="dashicons dashicons-align-none"></i> dashicons-align-none</option>
<option  value="align-right"><i class="dashicons dashicons-align-right"></i> dashicons-align-right</option>
<option  value="analytics"><i class="dashicons dashicons-analytics"></i> dashicons-analytics</option>
<option  value="archive"><i class="dashicons dashicons-archive"></i> dashicons-archive</option>
<option  value="arrow-down-alt"><i class="dashicons dashicons-arrow-down-alt"></i> dashicons-arrow-down-alt</option>
<option  value="arrow-down-alt2"><i class="dashicons dashicons-arrow-down-alt2"></i> dashicons-arrow-down-alt2</option>
<option  value="arrow-down"><i class="dashicons dashicons-arrow-down"></i> dashicons-arrow-down</option>
<option  value="arrow-left-alt"><i class="dashicons dashicons-arrow-left-alt"></i> dashicons-arrow-left-alt</option>
<option  value="arrow-left-alt2"><i class="dashicons dashicons-arrow-left-alt2"></i> dashicons-arrow-left-alt2</option>
<option  value="arrow-left"><i class="dashicons dashicons-arrow-left"></i> dashicons-arrow-left</option>
<option  value="arrow-right-alt"><i class="dashicons dashicons-arrow-right-alt"></i> dashicons-arrow-right-alt</option>
<option  value="arrow-right-alt2"><i class="dashicons dashicons-arrow-right-alt2"></i> dashicons-arrow-right-alt2</option>
<option  value="arrow-right"><i class="dashicons dashicons-arrow-right"></i> dashicons-arrow-right</option>
<option  value="arrow-up-alt"><i class="dashicons dashicons-arrow-up-alt"></i> dashicons-arrow-up-alt</option>
<option  value="arrow-up-alt2"><i class="dashicons dashicons-arrow-up-alt2"></i> dashicons-arrow-up-alt2</option>
<option  value="arrow-up"><i class="dashicons dashicons-arrow-up"></i> dashicons-arrow-up</option>
<option  value="art"><i class="dashicons dashicons-art"></i> dashicons-art</option>
<option  value="awards"><i class="dashicons dashicons-awards"></i> dashicons-awards</option>
<option  value="backup"><i class="dashicons dashicons-backup"></i> dashicons-backup</option>
<option  value="book-alt"><i class="dashicons dashicons-book-alt"></i> dashicons-book-alt</option>
<option  value="book"><i class="dashicons dashicons-book"></i> dashicons-book</option>
<option value="buddicons-activity"><i class="dashicons dashicons-buddicons-activity"></i> <em>dashicons-buddicons-activity</em></option>
<option value="buddicons-bbpress-logo"><i class="dashicons dashicons-buddicons-bbpress-logo"></i> <em>dashicons-buddicons-bbpress-logo</em></option>
<option value="buddicons-buddypress-logo"><i class="dashicons dashicons-buddicons-buddypress-logo"></i> <em>dashicons-buddicons-buddypress-logo</em></option>
<option value="buddicons-community"><i class="dashicons dashicons-buddicons-community"></i> <em>dashicons-buddicons-community</em></option>
<option value="buddicons-forums"><i class="dashicons dashicons-buddicons-forums"></i> <em>dashicons-buddicons-forums</em></option>
<option value="buddicons-friends"><i class="dashicons dashicons-buddicons-friends"></i> <em>dashicons-buddicons-friends</em></option>
<option value="buddicons-groups"><i class="dashicons dashicons-buddicons-groups"></i> <em>dashicons-buddicons-groups</em></option>
<option value="buddicons-pm"><i class="dashicons dashicons-buddicons-pm"></i> <em>dashicons-buddicons-pm</em></option>
<option value="buddicons-replies"><i class="dashicons dashicons-buddicons-replies"></i> <em>dashicons-buddicons-replies</em></option>
<option value="buddicons-topics"><i class="dashicons dashicons-buddicons-topics"></i> <em>dashicons-buddicons-topics</em></option>
<option value="buddicons-tracking"><i class="dashicons dashicons-buddicons-tracking"></i> <em>dashicons-buddicons-tracking</em></option>
<option  value="building"><i class="dashicons dashicons-building"></i> dashicons-building</option>
<option  value="businessman"><i class="dashicons dashicons-businessman"></i> dashicons-businessman</option>
<option  value="calendar-alt"><i class="dashicons dashicons-calendar-alt"></i> dashicons-calendar-alt</option>
<option  value="calendar"><i class="dashicons dashicons-calendar"></i> dashicons-calendar</option>
<option  value="camera"><i class="dashicons dashicons-camera"></i> dashicons-camera</option>
<option  value="carrot"><i class="dashicons dashicons-carrot"></i> dashicons-carrot</option>
<option  value="cart"><i class="dashicons dashicons-cart"></i> dashicons-cart</option>
<option  value="category"><i class="dashicons dashicons-category"></i> dashicons-category</option>
<option  value="chart-area"><i class="dashicons dashicons-chart-area"></i> dashicons-chart-area</option>
<option  value="chart-bar"><i class="dashicons dashicons-chart-bar"></i> dashicons-chart-bar</option>
<option  value="chart-line"><i class="dashicons dashicons-chart-line"></i> dashicons-chart-line</option>
<option  value="chart-pie"><i class="dashicons dashicons-chart-pie"></i> dashicons-chart-pie</option>
<option  value="clipboard"><i class="dashicons dashicons-clipboard"></i> dashicons-clipboard</option>
<option  value="clock"><i class="dashicons dashicons-clock"></i> dashicons-clock</option>
<option  value="cloud"><i class="dashicons dashicons-cloud"></i> dashicons-cloud</option>
<option  value="controls-back"><i class="dashicons dashicons-controls-back"></i> dashicons-controls-back</option>
<option  value="controls-forward"><i class="dashicons dashicons-controls-forward"></i> dashicons-controls-forward</option>
<option  value="controls-pause"><i class="dashicons dashicons-controls-pause"></i> dashicons-controls-pause</option>
<option  value="controls-play"><i class="dashicons dashicons-controls-play"></i> dashicons-controls-play</option>
<option  value="controls-repeat"><i class="dashicons dashicons-controls-repeat"></i> dashicons-controls-repeat</option>
<option  value="controls-skipback"><i class="dashicons dashicons-controls-skipback"></i> dashicons-controls-skipback</option>
<option  value="controls-skipforward"><i class="dashicons dashicons-controls-skipforward"></i> dashicons-controls-skipforward</option>
<option  value="controls-volumeoff"><i class="dashicons dashicons-controls-volumeoff"></i> dashicons-controls-volumeoff</option>
<option  value="controls-volumeon"><i class="dashicons dashicons-controls-volumeon"></i> dashicons-controls-volumeon</option>
<option  value="dashboard"><i class="dashicons dashicons-dashboard"></i> dashicons-dashboard</option>
<option  value="desktop"><i class="dashicons dashicons-desktop"></i> dashicons-desktop</option>
<option  value="dismiss"><i class="dashicons dashicons-dismiss"></i> dashicons-dismiss</option>
<option  value="download"><i class="dashicons dashicons-download"></i> dashicons-download</option>
<option  value="edit"><i class="dashicons dashicons-edit"></i> dashicons-edit</option>
<option  value="editor-aligncenter"><i class="dashicons dashicons-editor-aligncenter"></i> dashicons-editor-aligncenter</option>
<option  value="editor-alignleft"><i class="dashicons dashicons-editor-alignleft"></i> dashicons-editor-alignleft</option>
<option  value="editor-alignright"><i class="dashicons dashicons-editor-alignright"></i> dashicons-editor-alignright</option>
<option  value="editor-bold"><i class="dashicons dashicons-editor-bold"></i> dashicons-editor-bold</option>
<option  value="editor-break"><i class="dashicons dashicons-editor-break"></i> dashicons-editor-break</option>
<option  value="editor-code"><i class="dashicons dashicons-editor-code"></i> dashicons-editor-code</option>
<option  value="editor-contract"><i class="dashicons dashicons-editor-contract"></i> dashicons-editor-contract</option>
<option  value="editor-customchar"><i class="dashicons dashicons-editor-customchar"></i> dashicons-editor-customchar</option>
<option  value="editor-expand"><i class="dashicons dashicons-editor-expand"></i> dashicons-editor-expand</option>
<option  value="editor-help"><i class="dashicons dashicons-editor-help"></i> dashicons-editor-help</option>
<option  value="editor-indent"><i class="dashicons dashicons-editor-indent"></i> dashicons-editor-indent</option>
<option  value="editor-insertmore"><i class="dashicons dashicons-editor-insertmore"></i> dashicons-editor-insertmore</option>
<option  value="editor-italic"><i class="dashicons dashicons-editor-italic"></i> dashicons-editor-italic</option>
<option  value="editor-justify"><i class="dashicons dashicons-editor-justify"></i> dashicons-editor-justify</option>
<option  value="editor-kitchensink"><i class="dashicons dashicons-editor-kitchensink"></i> dashicons-editor-kitchensink</option>
<option value="editor-ltr"><i class="dashicons dashicons-editor-ltr"></i> <em>dashicons-editor-ltr</em></option>
<option  value="editor-ol"><i class="dashicons dashicons-editor-ol"></i> dashicons-editor-ol</option>
<option  value="editor-outdent"><i class="dashicons dashicons-editor-outdent"></i> dashicons-editor-outdent</option>
<option  value="editor-paragraph"><i class="dashicons dashicons-editor-paragraph"></i> dashicons-editor-paragraph</option>
<option  value="editor-paste-text"><i class="dashicons dashicons-editor-paste-text"></i> dashicons-editor-paste-text</option>
<option  value="editor-paste-word"><i class="dashicons dashicons-editor-paste-word"></i> dashicons-editor-paste-word</option>
<option  value="editor-quote"><i class="dashicons dashicons-editor-quote"></i> dashicons-editor-quote</option>
<option  value="editor-removeformatting"><i class="dashicons dashicons-editor-removeformatting"></i> dashicons-editor-removeformatting</option>
<option  value="editor-rtl"><i class="dashicons dashicons-editor-rtl"></i> dashicons-editor-rtl</option>
<option  value="editor-spellcheck"><i class="dashicons dashicons-editor-spellcheck"></i> dashicons-editor-spellcheck</option>
<option  value="editor-strikethrough"><i class="dashicons dashicons-editor-strikethrough"></i> dashicons-editor-strikethrough</option>
<option  value="editor-table"><i class="dashicons dashicons-editor-table"></i> dashicons-editor-table</option>
<option  value="editor-textcolor"><i class="dashicons dashicons-editor-textcolor"></i> dashicons-editor-textcolor</option>
<option  value="editor-ul"><i class="dashicons dashicons-editor-ul"></i> dashicons-editor-ul</option>
<option  value="editor-underline"><i class="dashicons dashicons-editor-underline"></i> dashicons-editor-underline</option>
<option  value="editor-unlink"><i class="dashicons dashicons-editor-unlink"></i> dashicons-editor-unlink</option>
<option  value="editor-video"><i class="dashicons dashicons-editor-video"></i> dashicons-editor-video</option>
<option  value="email-alt"><i class="dashicons dashicons-email-alt"></i> dashicons-email-alt</option>
<option value="email-alt2"><i class="dashicons dashicons-email-alt2"></i> <em>dashicons-email-alt2</em></option>
<option  value="email"><i class="dashicons dashicons-email"></i> dashicons-email</option>
<option  value="excerpt-view"><i class="dashicons dashicons-excerpt-view"></i> dashicons-excerpt-view</option>
<option  value="external"><i class="dashicons dashicons-external"></i> dashicons-external</option>
<option  value="facebook-alt"><i class="dashicons dashicons-facebook-alt"></i> dashicons-facebook-alt</option>
<option  value="facebook"><i class="dashicons dashicons-facebook"></i> dashicons-facebook</option>
<option  value="feedback"><i class="dashicons dashicons-feedback"></i> dashicons-feedback</option>
<option  value="filter"><i class="dashicons dashicons-filter"></i> dashicons-filter</option>
<option  value="flag"><i class="dashicons dashicons-flag"></i> dashicons-flag</option>
<option  value="format-aside"><i class="dashicons dashicons-format-aside"></i> dashicons-format-aside</option>
<option  value="format-audio"><i class="dashicons dashicons-format-audio"></i> dashicons-format-audio</option>
<option  value="format-chat"><i class="dashicons dashicons-format-chat"></i> dashicons-format-chat</option>
<option  value="format-gallery"><i class="dashicons dashicons-format-gallery"></i> dashicons-format-gallery</option>
<option  value="format-image"><i class="dashicons dashicons-format-image"></i> dashicons-format-image</option>
<option  value="format-quote"><i class="dashicons dashicons-format-quote"></i> dashicons-format-quote</option>
<option  value="format-status"><i class="dashicons dashicons-format-status"></i> dashicons-format-status</option>
<option  value="format-video"><i class="dashicons dashicons-format-video"></i> dashicons-format-video</option>
<option  value="forms"><i class="dashicons dashicons-forms"></i> dashicons-forms</option>
<option  value="googleplus"><i class="dashicons dashicons-googleplus"></i> dashicons-googleplus</option>
<option  value="grid-view"><i class="dashicons dashicons-grid-view"></i> dashicons-grid-view</option>
<option  value="groups"><i class="dashicons dashicons-groups"></i> dashicons-groups</option>
<option  value="hammer"><i class="dashicons dashicons-hammer"></i> dashicons-hammer</option>
<option  value="heart"><i class="dashicons dashicons-heart"></i> dashicons-heart</option>
<option  value="hidden"><i class="dashicons dashicons-hidden"></i> dashicons-hidden</option>
<option  value="id-alt"><i class="dashicons dashicons-id-alt"></i> dashicons-id-alt</option>
<option  value="id"><i class="dashicons dashicons-id"></i> dashicons-id</option>
<option  value="image-crop"><i class="dashicons dashicons-image-crop"></i> dashicons-image-crop</option>
<option  value="image-filter"><i class="dashicons dashicons-image-filter"></i> dashicons-image-filter</option>
<option  value="image-flip-horizontal"><i class="dashicons dashicons-image-flip-horizontal"></i> dashicons-image-flip-horizontal</option>
<option  value="image-flip-vertical"><i class="dashicons dashicons-image-flip-vertical"></i> dashicons-image-flip-vertical</option>
<option  value="image-rotate-left"><i class="dashicons dashicons-image-rotate-left"></i> dashicons-image-rotate-left</option>
<option  value="image-rotate-right"><i class="dashicons dashicons-image-rotate-right"></i> dashicons-image-rotate-right</option>
<option  value="image-rotate"><i class="dashicons dashicons-image-rotate"></i> dashicons-image-rotate</option>
<option  value="images-alt"><i class="dashicons dashicons-images-alt"></i> dashicons-images-alt</option>
<option  value="images-alt2"><i class="dashicons dashicons-images-alt2"></i> dashicons-images-alt2</option>
<option  value="index-card"><i class="dashicons dashicons-index-card"></i> dashicons-index-card</option>
<option  value="info"><i class="dashicons dashicons-info"></i> dashicons-info</option>
<option  value="laptop"><i class="dashicons dashicons-laptop"></i> dashicons-laptop</option>
<option  value="layout"><i class="dashicons dashicons-layout"></i> dashicons-layout</option>
<option  value="leftright"><i class="dashicons dashicons-leftright"></i> dashicons-leftright</option>
<option  value="lightbulb"><i class="dashicons dashicons-lightbulb"></i> dashicons-lightbulb</option>
<option  value="list-view"><i class="dashicons dashicons-list-view"></i> dashicons-list-view</option>
<option  value="location-alt"><i class="dashicons dashicons-location-alt"></i> dashicons-location-alt</option>
<option  value="location"><i class="dashicons dashicons-location"></i> dashicons-location</option>
<option  value="lock"><i class="dashicons dashicons-lock"></i> dashicons-lock</option>
<option  value="marker"><i class="dashicons dashicons-marker"></i> dashicons-marker</option>
<option  value="media-archive"><i class="dashicons dashicons-media-archive"></i> dashicons-media-archive</option>
<option  value="media-audio"><i class="dashicons dashicons-media-audio"></i> dashicons-media-audio</option>
<option  value="media-code"><i class="dashicons dashicons-media-code"></i> dashicons-media-code</option>
<option  value="media-default"><i class="dashicons dashicons-media-default"></i> dashicons-media-default</option>
<option  value="media-document"><i class="dashicons dashicons-media-document"></i> dashicons-media-document</option>
<option  value="media-interactive"><i class="dashicons dashicons-media-interactive"></i> dashicons-media-interactive</option>
<option  value="media-spreadsheet"><i class="dashicons dashicons-media-spreadsheet"></i> dashicons-media-spreadsheet</option>
<option  value="media-text"><i class="dashicons dashicons-media-text"></i> dashicons-media-text</option>
<option  value="media-video"><i class="dashicons dashicons-media-video"></i> dashicons-media-video</option>
<option  value="megaphone"><i class="dashicons dashicons-megaphone"></i> dashicons-megaphone</option>
<option  value="menu-alt"><i class="dashicons dashicons-menu-alt"></i> <em>dashicons-menu-alt</em></option>
<option  value="menu"><i class="dashicons dashicons-menu"></i> dashicons-menu</option>
<option  value="microphone"><i class="dashicons dashicons-microphone"></i> dashicons-microphone</option>
<option  value="migrate"><i class="dashicons dashicons-migrate"></i> dashicons-migrate</option>
<option  value="minus"><i class="dashicons dashicons-minus"></i> dashicons-minus</option>
<option  value="money"><i class="dashicons dashicons-money"></i> dashicons-money</option>
<option  value="move"><i class="dashicons dashicons-move"></i> dashicons-move</option>
<option  value="nametag"><i class="dashicons dashicons-nametag"></i> dashicons-nametag</option>
<option  value="networking"><i class="dashicons dashicons-networking"></i> dashicons-networking</option>
<option  value="no-alt"><i class="dashicons dashicons-no-alt"></i> dashicons-no-alt</option>
<option  value="no"><i class="dashicons dashicons-no"></i> dashicons-no</option>
<option  value="palmtree"><i class="dashicons dashicons-palmtree"></i> dashicons-palmtree</option>
<option  value="paperclip"><i class="dashicons dashicons-paperclip"></i> dashicons-paperclip</option>
<option  value="performance"><i class="dashicons dashicons-performance"></i> dashicons-performance</option>
<option  value="phone"><i class="dashicons dashicons-phone"></i> dashicons-phone</option>
<option  value="playlist-audio"><i class="dashicons dashicons-playlist-audio"></i> dashicons-playlist-audio</option>
<option  value="playlist-video"><i class="dashicons dashicons-playlist-video"></i> dashicons-playlist-video</option>
<option  value="plus-alt"><i class="dashicons dashicons-plus-alt"></i> dashicons-plus-alt</option>
<option value="plus-light"><i class="dashicons dashicons-plus-light"></i> <em>dashicons-plus-light</em></option>
<option  value="plus"><i class="dashicons dashicons-plus"></i> dashicons-plus</option>
<option  value="portfolio"><i class="dashicons dashicons-portfolio"></i> dashicons-portfolio</option>
<option  value="post-status"><i class="dashicons dashicons-post-status"></i> dashicons-post-status</option>
<option  value="pressthis"><i class="dashicons dashicons-pressthis"></i> dashicons-pressthis</option>
<option  value="products"><i class="dashicons dashicons-products"></i> dashicons-products</option>
<option  value="randomize"><i class="dashicons dashicons-randomize"></i> dashicons-randomize</option>
<option  value="redo"><i class="dashicons dashicons-redo"></i> dashicons-redo</option>
<option value="rest-api"><i class="dashicons dashicons-rest-api"></i> <em>dashicons-rest-api</em></option>
<option  value="rss"><i class="dashicons dashicons-rss"></i> dashicons-rss</option>
<option  value="schedule"><i class="dashicons dashicons-schedule"></i> dashicons-schedule</option>
<option  value="screenoptions"><i class="dashicons dashicons-screenoptions"></i> dashicons-screenoptions</option>
<option  value="search"><i class="dashicons dashicons-search"></i> dashicons-search</option>
<option  value="share-alt"><i class="dashicons dashicons-share-alt"></i> dashicons-share-alt</option>
<option  value="share-alt2"><i class="dashicons dashicons-share-alt2"></i> dashicons-share-alt2</option>
<option  value="share"><i class="dashicons dashicons-share"></i> dashicons-share</option>
<option  value="shield-alt"><i class="dashicons dashicons-shield-alt"></i> dashicons-shield-alt</option>
<option  value="shield"><i class="dashicons dashicons-shield"></i> dashicons-shield</option>
<option  value="slides"><i class="dashicons dashicons-slides"></i> dashicons-slides</option>
<option  value="smartphone"><i class="dashicons dashicons-smartphone"></i> dashicons-smartphone</option>
<option  value="smiley"><i class="dashicons dashicons-smiley"></i> dashicons-smiley</option>
<option  value="sort"><i class="dashicons dashicons-sort"></i> dashicons-sort</option>
<option  value="sos"><i class="dashicons dashicons-sos"></i> dashicons-sos</option>
<option  value="star-empty"><i class="dashicons dashicons-star-empty"></i> dashicons-star-empty</option>
<option  value="star-filled"><i class="dashicons dashicons-star-filled"></i> dashicons-star-filled</option>
<option  value="star-half"><i class="dashicons dashicons-star-half"></i> dashicons-star-half</option>
<option  value="sticky"><i class="dashicons dashicons-sticky"></i> dashicons-sticky</option>
<option  value="store"><i class="dashicons dashicons-store"></i> dashicons-store</option>
<option  value="tablet"><i class="dashicons dashicons-tablet"></i> dashicons-tablet</option>
<option  value="tag"><i class="dashicons dashicons-tag"></i> dashicons-tag</option>
<option  value="tagcloud"><i class="dashicons dashicons-tagcloud"></i> dashicons-tagcloud</option>
<option  value="testimonial"><i class="dashicons dashicons-testimonial"></i> dashicons-testimonial</option>
<option  value="text"><i class="dashicons dashicons-text"></i> dashicons-text</option>
<option  value="thumbs-down"><i class="dashicons dashicons-thumbs-down"></i> dashicons-thumbs-down</option>
<option  value="thumbs-up"><i class="dashicons dashicons-thumbs-up"></i> dashicons-thumbs-up</option>
<option  value="tickets-alt"><i class="dashicons dashicons-tickets-alt"></i> dashicons-tickets-alt</option>
<option  value="tickets"><i class="dashicons dashicons-tickets"></i> dashicons-tickets</option>
<option value="tide"><i class="dashicons dashicons-tide"></i> <em>dashicons-tide</em></option>
<option  value="translation"><i class="dashicons dashicons-translation"></i> dashicons-translation</option>
<option  value="trash"><i class="dashicons dashicons-trash"></i> dashicons-trash</option>
<option  value="twitter"><i class="dashicons dashicons-twitter"></i> dashicons-twitter</option>
<option  value="undo"><i class="dashicons dashicons-undo"></i> dashicons-undo</option>
<option  value="universal-access-alt"><i class="dashicons dashicons-universal-access-alt"></i> dashicons-universal-access-alt</option>
<option  value="universal-access"><i class="dashicons dashicons-universal-access"></i> dashicons-universal-access</option>
<option  value="unlock"><i class="dashicons dashicons-unlock"></i> dashicons-unlock</option>
<option  value="update"><i class="dashicons dashicons-update"></i> dashicons-update</option>
<option  value="upload"><i class="dashicons dashicons-upload"></i> dashicons-upload</option>
<option  value="vault"><i class="dashicons dashicons-vault"></i> dashicons-vault</option>
<option  value="video-alt"><i class="dashicons dashicons-video-alt"></i> dashicons-video-alt</option>
<option  value="video-alt2"><i class="dashicons dashicons-video-alt2"></i> dashicons-video-alt2</option>
<option  value="video-alt3"><i class="dashicons dashicons-video-alt3"></i> dashicons-video-alt3</option>
<option  value="visibility"><i class="dashicons dashicons-visibility"></i> dashicons-visibility</option>
<option  value="warning"><i class="dashicons dashicons-warning"></i> dashicons-warning</option>
<option  value="welcome-add-page"><i class="dashicons dashicons-welcome-add-page"></i> dashicons-welcome-add-page</option>
<option  value="welcome-comments"><i class="dashicons dashicons-welcome-comments"></i> dashicons-welcome-comments</option>
<option  value="welcome-learn-more"><i class="dashicons dashicons-welcome-learn-more"></i> dashicons-welcome-learn-more</option>
<option  value="welcome-view-site"><i class="dashicons dashicons-welcome-view-site"></i> dashicons-welcome-view-site</option>
<option  value="welcome-widgets-menus"><i class="dashicons dashicons-welcome-widgets-menus"></i> dashicons-welcome-widgets-menus</option>
<option  value="welcome-write-blog"><i class="dashicons dashicons-welcome-write-blog"></i> dashicons-welcome-write-blog</option>
<option  value="wordpress-alt"><i class="dashicons dashicons-wordpress-alt"></i> dashicons-wordpress-alt</option>
<option  value="wordpress"><i class="dashicons dashicons-wordpress"></i> dashicons-wordpress</option>
<option value="yes-alt"><i class="dashicons dashicons-yes-alt"></i> <em>dashicons-yes-alt</em></option>
<option  value="yes"><i class="dashicons dashicons-yes"></i> dashicons-yes</option>
</select>